const QUIZSTORENAME = 'QUIZESTORE'
const QUIZESTOREPREFIX = 'QUIZ'
const QUESTIONSTORENAME = 'QUESTIONESTORE'
const QUESTIONESTOREPREFIX = 'QUESTION'
const MAXQUIESTIONCOUNT = 10
const MINQUIESTIONCOUNT = 2
const module = {
  MINQUIESTIONCOUNT,
  MAXQUIESTIONCOUNT,
  QUIZSTORENAME,
  QUIZESTOREPREFIX,
  QUESTIONSTORENAME,
  QUESTIONESTOREPREFIX
}

export default module
